Repository g6jamm/stima, pull requests merged in 2021-12, with the labels that each got.

#44 Isloggedin
  src/main/java/com/g6jamm/stima/web/UserController.java
Labels: enhancement

#43 Staticmemory
  src/main/java/com/g6jamm/stima/data/repository/mock/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/mock/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/mock/UserRepositoryStub.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: bug-fix, enhancement

#45 Abspro
  src/main/java/com/g6jamm/stima/data/repository/mock/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/mock/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
Labels: new-feature

#46 Change mock to stub
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: bug-fix

#47 Resource type
  src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/exception/ResourceTypeNotFoundException.java
  src/main/java/com/g6jamm/stima/domain/exception/TaskCreationException.java
  src/main/java/com/g6jamm/stima/domain/model/ResourceType.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/templates/Task.html
  src/main/resources/templates/project.html
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: enhancement, new-feature

#48 Sub test
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/test/java/com/g6jamm/stima/domain/service/SubProjectTest.java
Labels: enhancement

#49 new index page
  src/main/resources/static/assets/brand/squidlogo.png
  src/main/resources/static/signin.css
  src/main/resources/templates/index.html
Labels: enhancement

#51 Sub page
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/templates/project.html
  src/main/resources/templates/subProject.html
Labels: bug-fix, new-feature

#52 Sub color
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/templates/project.html
  src/main/resources/templates/subProject.html
Labels: enhancement

#53 SQL install script
  install.sh
  src/main/resources/data/install.sql
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
Labels: new-feature

#55 Use fragments on index page and fix css to work with global css
  src/main/resources/static/css/signin.css
  src/main/resources/static/img/logo.png
  src/main/resources/static/signin.css
  src/main/resources/templates/fragments/footerFragtment.html
  src/main/resources/templates/index.html
Labels: enhancement, new-feature

#54 Change order of drop tables
  src/main/resources/static/data/install.sql
Labels: bug-fix

#56 Added fragtments and modal boxes
  src/main/java/com/g6jamm/stima/data/repository/ProjectColorRepository.java
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/static/css/global.css
  src/main/resources/templates/Task.html
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/footerFragtment.html
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/navFragment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/fragments/taskModalFragment.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
  src/test/java/com/g6jamm/stima/domain/service/SubProjectTest.java
Labels: bug-fix, enhancement, new-feature

#57 Add connection to DB
  src/main/java/com/g6jamm/stima/data/repository/util/DbManager.java
  src/main/java/com/g6jamm/stima/data/repository/util/DbSelector.java
  src/main/java/com/g6jamm/stima/data/repository/util/type/ConnectionType.java
Labels: new-feature

#61 User db
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/web/UserController.java
Labels: enhancement, new-feature

#62 Addtasktoproject
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectInterface.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
Labels: enhancement

#58 remove unused variable from application.properties
  install.sh
Labels: enhancement

#60 Update link to prod
  README.md
Labels: bug-fix

#63 fixed naming in script
  src/main/resources/static/data/install.sql
Labels: bug-fix

#64 Sub sql
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
Labels: new-feature

#69 Task sql
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectInterface.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: enhancement

#70 Added total calculation
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/templates/fragments/projectFragment.html
Labels: new-feature

#71 Project SQL
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/static/data/sample-data.sql
Labels: new-feature

#73 fixed bug where lists where null
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/static/data/sample-data.sql
Labels: bug-fix

#75 Workday and ressource calc - still needs work
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/SubProject.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
Labels: enhancement

#83 Composite
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectInterface.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/test/java/com/g6jamm/stima/domain/service/ProjectLeafTest.java
Labels: enhancement

#74 Change ubuntu version
  .github/workflows/javaformat.yml
  .github/workflows/maven.yml
  .github/workflows/pull_request_target.yml
Labels: bug-fix

#84 Display projects per user
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
Labels: enhancement, new-feature

#85 Add edit/delete option to projects
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/static/css/global.css
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
  src/main/resources/templates/fragments/footerFragtment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
Labels: new-feature

#88 Task edit2
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/static/data/sample-data.sql
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/project.html
  src/main/resources/templates/subProject.html
Labels: new-feature

#89 Fix plus card size
  src/main/resources/static/css/global.css
  src/main/resources/templates/projects.html
Labels: new-feature

#87 Exceptions
  src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: enhancement

#91 Fix colors using MySQL impl
  src/main/java/com/g6jamm/stima/data/repository/ProjectColorRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/static/css/global.css
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
Labels: bug-fix

#92 Fix dependency injections
  src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: enhancement

#94 Exceptions2
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
Labels: bug-fix, enhancement

#96 Validation
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/fragments/taskModalFragment.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
Labels: bug-fix

#101 Fix create user
  src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
  src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/model/User.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/static/data/sample-data.sql
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/projects.html
Labels: bug-fix

#107 Fix db for Heroku
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
Labels: bug-fix

#116 Fix #112
  src/main/resources/static/css/global.css
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
Labels: bug-fix

#114 Fix #111
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
Labels: bug-fix

#115 Fix #110
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/project.html
  src/main/resources/templates/subProject.html
Labels: bug-fix

#118 Fix translation
  src/main/resources/templates/createUser.html
  src/main/resources/templates/fragments/navFragment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
Labels: bug-fix

#119 Fix empty btn cards
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
Labels: bug-fix

#120 Use user object instead of id in session
  src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
Labels: bug-fix

#121 Create user from admin page
  src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/templates/fragments/navFragment.html
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
Labels: bug-fix

#122 Improve MySql calls
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
Labels: bug-fix

#123 Fix create user
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/static/css/createUser.css
  src/main/resources/static/css/global.css
  src/main/resources/static/css/signin.css
  src/main/resources/templates/createUser.html
  src/main/resources/templates/fragments/createUserFragment.html
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/navFragment.html
Labels: bug-fix

#128 Testing new version
  src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/static/css/createUser.css
  src/main/resources/static/css/global.css
  src/main/resources/static/css/signin.css
  src/main/resources/static/data/install.sql
  src/main/resources/static/data/sample-data.sql
  src/main/resources/templates/createUser.html
  src/main/resources/templates/fragments/createUserFragment.html
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/navFragment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
Labels: enhancement

#135 Google lighthouse
  src/main/resources/static/css/global.css
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/index.html
Labels: bug-fix

#134 Wrong resource name
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
Labels: bug-fix

#136 Fix all W3C validate warnings/erros
  src/main/resources/templates/fragments/createUserFragment.html
  src/main/resources/templates/fragments/headFragment.html
  src/main/resources/templates/fragments/navFragment.html
  src/main/resources/templates/fragments/projectFragment.html
  src/main/resources/templates/fragments/taskFragment.html
  src/main/resources/templates/fragments/taskModalFragment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/project.html
  src/main/resources/templates/projects.html
  src/main/resources/templates/subProject.html
Labels: bug-fix

#138 Fix delete task
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/resources/templates/fragments/taskFragment.html
Labels: bug-fix

#141 Add footer to container and fix logo text
  src/main/resources/templates/fragments/footerFragtment.html
  src/main/resources/templates/fragments/navFragment.html
Labels: bug-fix

#143 More tests
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
  src/test/java/com/g6jamm/stima/domain/service/ProjectColorServiceTest.java
  src/test/java/com/g6jamm/stima/domain/service/ProjectLeafTest.java
  src/test/java/com/g6jamm/stima/domain/service/ProjectServiceTest.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
  src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
Labels: enhancement

#146 Javadocs
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/model/Headproject.java
  src/main/java/com/g6jamm/stima/domain/model/User.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
Labels: bug-fix, enhancement

#147 Add IT test
  pom.xml
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/test/java/com/g6jamm/stima/data/repository/mysql/util/DbManagerTest.java
  src/test/java/com/g6jamm/stima/domain/service/TaskServiceTest.java
Labels: bug-fix

#148 Java docs
  README.md
  img.png
  img_1.png
  pom.xml
  src/main/java/com/g6jamm/stima/data/repository/mysql/PermissionRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/RoleRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/exception/LoginException.java
  src/main/java/com/g6jamm/stima/domain/exception/ResourceTypeNotFoundException.java
  src/main/java/com/g6jamm/stima/domain/exception/SignUpException.java
  src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
  src/main/java/com/g6jamm/stima/domain/exception/TaskCreationException.java
  src/main/java/com/g6jamm/stima/domain/model/Headproject.java
  src/main/java/com/g6jamm/stima/domain/model/Permission.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/ResourceType.java
  src/main/java/com/g6jamm/stima/domain/model/Role.java
  src/main/java/com/g6jamm/stima/domain/model/Subproject.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/model/User.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/resources/static/data/sample-data.sql
Labels: enhancement

#149 Run tests
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
Labels: bug-fix

#150 fix tests
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
Labels: bug-fix

#153 Deployment
  README.md
  pom.xml
  src/main/java/com/g6jamm/stima/data/repository/PermissionRepository.java
  src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
  src/main/java/com/g6jamm/stima/data/repository/RoleRepository.java
  src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
  src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
  src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/PermissionRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/RoleRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/util/DbManager.java
  src/main/java/com/g6jamm/stima/data/repository/mysql/util/DbSelector.java
  src/main/java/com/g6jamm/stima/data/repository/stub/PermissionRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/RoleRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
  src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
  src/main/java/com/g6jamm/stima/domain/exception/LoginException.java
  src/main/java/com/g6jamm/stima/domain/exception/ResourceTypeNotFoundException.java
  src/main/java/com/g6jamm/stima/domain/exception/SignUpException.java
  src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
  src/main/java/com/g6jamm/stima/domain/exception/TaskCreationException.java
  src/main/java/com/g6jamm/stima/domain/model/Headproject.java
  src/main/java/com/g6jamm/stima/domain/model/Permission.java
  src/main/java/com/g6jamm/stima/domain/model/Project.java
  src/main/java/com/g6jamm/stima/domain/model/ResourceType.java
  src/main/java/com/g6jamm/stima/domain/model/Role.java
  src/main/java/com/g6jamm/stima/domain/model/Subproject.java
  src/main/java/com/g6jamm/stima/domain/model/Task.java
  src/main/java/com/g6jamm/stima/domain/model/User.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
  src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
  src/main/java/com/g6jamm/stima/domain/service/TaskService.java
  src/main/java/com/g6jamm/stima/domain/service/UserService.java
  src/main/java/com/g6jamm/stima/web/ProjectController.java
  src/main/java/com/g6jamm/stima/web/SubProjectController.java
  src/main/java/com/g6jamm/stima/web/UserController.java
  src/main/resources/static/data/sample-data.sql
  src/test/java/com/g6jamm/stima/data/repository/mysql/util/DbManagerTest.java
  src/test/java/com/g6jamm/stima/domain/service/TaskServiceTest.java
  src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
Labels: bug-fix, enhancement, new-feature

#154 fix delete task for subproject
  src/main/resources/templates/subProject.html
Labels: bug-fix

#155 Deployment
  src/main/resources/templates/subProject.html
Labels: bug-fix
